version: '2'  
services:  
  php-fpm:
    build: ./docker/php/
    environment:
      TIMEZONE: Europe/Paris
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./app:/var/www/app
      - ./docker/logs/symfony:/var/www/symfony/app/logs
    working_dir: /var/www/app
    depends_on:
      - mariadb
    volumes_from:
      - data
    tty: true

  nginx:
    image: nginx
    depends_on:
      - php-fpm
    volumes_from:
      - php-fpm
      - data
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 8081:8081

  composer:
    image: composer:1.4
    volumes_from:
      - php-fpm
    working_dir: /var/www/app

  mariadb:
    image: mariadb:10.1
    ports:
        - 3306:3306
    environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
    volumes_from:
        - data

  data:
    image: debian
    working_dir: /
    volumes:
        - /var/lib/mysql
        - /var/log/nginx
        - /data
    tty: true